### ISSUE TITLE
Quick draft final presentation - advice

### ISSUE THREAD

**Issue by masongallo** [rogeliozunigarubio/data_science_final_project#1]
Quick and easy:

I think it's a bit too difficult to follow your research question slide. Try making that slide with a bit less words. Once you have that down, I would also focus on a slide where you describe/define the response variable. It may even help to have a "brief" data dictionary. Unsupervised methods might be interesting here as well, especially LDA and k-means.

**Comment by rogeliozunigarubio** [comment]
thank you, when can I get guidance from you on using LDA and k-means, I have been struggling with what else to do with the data other than compute a sentiment score.
